feat: Add deprecation warnings to Steps from Apps components and Docs
slackapi/bolt-python pull request #1089
Opened 2024-06-06 17:07 UTC by WilliamBergamin

This PR aims to inform developers that steps from apps are deprecated
- Add a deprecation notice in the `docstring` of steps from apps components 
- Adds a runtime deprecation warning displayed whenever the step handler is invoked
- Adds deprecation notice in the `examples`
- Adds a deprecation notice to the `slack.dev`

| Before | After |
|---|---|
| <img width="2560" alt="Screenshot 2024-06-06 at 12 51 36 PM" src="https://github.com/slackapi/bolt-python/assets/25348381/e766427b-a131-4eab-848c-f0d0624f891c"> | <img width="2558" alt="Screenshot 2024-06-06 at 12 51 04 PM" src="https://github.com/slackapi/bolt-python/assets/25348381/78d3d0df-6daf-4065-8ef8-bd648781ad7a"> |

### Category

* [x] `slack_bolt.App` and/or its core components
* [x] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [x] Document pages under `/docs`
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2024-06-06 23:57 UTC, seratch approved these changes
Thanks for working on this! Once the Japanese label is fixed, you can go ahead with these changes!

2024-06-06 23:57 UTC, seratch commented on docs/_config.yml
> +    deprecated: 使用されていない
```suggestion
    deprecated: 非推奨
```

2024-06-06 23:58 UTC, seratch commented on docs/_config.yml
> +    deprecated: 使用されていない
Updated!

2024-06-07 12:51 UTC, filmaj requested changes
Left a minor URL typo

2024-06-07 12:51 UTC, filmaj commented on docs/_steps/workflow_steps_overview.md
> +Steps from Apps for legacy workflows are now deprecated. Use new [custom steps](https://api.slack.com/automation/functions/custom-bol).
```suggestion
Steps from Apps for legacy workflows are now deprecated. Use new [custom steps](https://api.slack.com/automation/functions/custom-bolt).
```

2024-06-07 13:32 UTC, merged