chore: move to mypy
slackapi/bolt-python pull request #1130
Opened 2024-08-15 21:43 UTC by WilliamBergamin

WORK IN PROGRESS

[MyPy](https://mypy.readthedocs.io/en/latest/index.html) was found to execute much fast the [PyType](https://google.github.io/pytype/) in this project, these changes adapt the project to use MyPy instead of PyType

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [x] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2024-08-16 17:19 UTC, WilliamBergamin commented on slack_bolt/middleware/authorization/async_multi_teams_authorization.py
> +                if req.context.response_url is not None and callable(req.context.respond):
I don't think this should change the current behavior of the code base and it should make it more resilient, but asserting callable is another option
 ```suggestion
 if req.context.response_url is not None:
         assert callable(req.context.respond), "req.context.respond must be callable"
```

2024-08-16 17:19 UTC, WilliamBergamin commented on slack_bolt/oauth/async_oauth_flow.py
> +            self.settings.logger = self._logger
`self.settings.logger` should never be `None`

2024-08-16 18:59 UTC, filmaj commented
My goodness from 11 minutes to 40 seconds 🤯

2024-08-16 20:07 UTC, filmaj reviewed
Nicely done! The speed boosts are significant so it seems like a good change, but I will defer to Kaz's opinion on this - so will not put a checkmark on it 😄 sorry!

2024-08-16 20:07 UTC, filmaj commented on slack_bolt/app/app.py
> +        installation_store_bot_only: bool = False,
Seems odd to have an optional boolean, unless the None state has a special meaning and so `installation_store_bot_only` is meant to have one of three states?

2024-08-19 08:06 UTC, seratch requested changes
@WilliamBergamin Great work! 

The reasons why I chose pytype over mypy during the initial development of bolt-python a few years ago are:
- I compared mypy, pyright, and pytype; for this project, pytype was the most intelligent. It detected many type hint issues by analyzing method calls within bolt-python and test code. Slow execution was already a concern, but running it on CI builds was acceptable. Pyright looked good too, but it was not as helpful for this project in terms of the number of error/mistake detections.
- Back then, mypy displayed way more unhelpful errors than other tools. During active development, I didn't have time to handle that. Also, pytype was significantly smarter for many patterns then.

Pytype was incredibly helpful, especially for the initial development, but I notice that it does not detect many issues anymore because this project is very stable and there are fewer type hint errors now. For this stage, I am open to prioritizing execution speed over the linter's intelligence.

2024-08-19 16:35 UTC, WilliamBergamin commented on slack_bolt/app/app.py
> +        elif self._authorize is not None:
Great suggestion, I've added a BoltError exception, but I'm unsure of its message

```py
        else:
            raise BoltError("OAuthFlow or Authorize must be configured to make a Bolt app")
```

Let me know if this is sufficient 🤔

2024-08-19 16:47 UTC, WilliamBergamin commented on slack_bolt/listener/async_listener_error_handler.py
> +            assert response is not None, "response should never be 'None' here"
This change was intentional, `mypy` believes that `response` can be None in this situation, but I can revert this

2024-08-19 16:56 UTC, WilliamBergamin commented on slack_bolt/middleware/authorization/async_multi_teams_authorization.py
> +                if req.context.response_url is not None and callable(req.context.respond):
Sounds good 💯 I will remove the `assert` changes and add `type: ignore` statements when needed

2024-08-19 17:20 UTC, WilliamBergamin commented on slack_bolt/logger/messages.py
> +            action_id_or_callback_id = req.body.get("actions", [])[0].get("action_id")
I agree, it appears the following satisfies mypy

```py
req.body["actions"][0].get("action_id")
```

2024-08-19 17:22 UTC, WilliamBergamin commented on slack_bolt/logger/messages.py
> +            constraints = '"' + req.body.get("action_id", "") + '"'
Same here also it seems the following satisfies mypy

```py
constraints = '"' + req.body["action_id"] + '"'
```

2024-08-20 15:29 UTC, WilliamBergamin commented
@seratch thank you for sharing the context behind originally choosing pytype over mypy, now that I've used both libraries I see how pytype is more intelligent and covers more patterns  then mypy, I assume this gap was larger in the past. I see how useful this can be in the early stages this project 🙇 

Simultaneously mypy did catch a few edge cases that I was not aware of and may be worth addressing in the future. For [example](https://github.com/slackapi/bolt-python/blob/40f6d1e46cdf8f958ad682c9ae0aeb73d27ce616/slack_bolt/context/context.py#L37) the `context.client` is `optional` this has ripple effects in the project since it regularly assumes the client value is not `None`

2024-08-20 22:59 UTC, seratch approved these changes
Left one last comment about the error message string. After resolving it, you can merge this PR tomorrow in your timezone! Thanks for making these changes!

2024-08-20 22:59 UTC, seratch commented on slack_bolt/app/app.py
> +        elif self._authorize is not None:
The error message looks good to me. For consistency, move the string to `slack_bolt.logger.messages` like other parts in this class do!

2024-08-20 22:59 UTC, seratch commented on slack_bolt/app/app.py
> +            raise BoltError("OAuthFlow or Authorize must be configured to make a Bolt app")
move the string to slack_bolt.logger.messages

2024-08-20 22:59 UTC, seratch commented on slack_bolt/app/async_app.py
> +            raise BoltError("OAuthFlow or Authorize must be configured to make a Bolt app")
same as above

2024-08-21 07:27 UTC, seratch commented
@WilliamBergamin Can you merge https://github.com/slackapi/bolt-python/pull/1132 first if it looks good to you? The changes by that PR may cause conflicts with this PR. If that's the case, please resolve it on this PR side 🙏

2024-08-21 14:40 UTC, merged