Revise README
slackapi/bolt-python pull request #115
Opened 2020-10-05 19:31 UTC by shaydewael

This PR modifies the README to include more information about available listeners and available utility functions. It also does a little bit of reorganizing of the README's order

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [x] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2020-10-05 20:18 UTC, mwbrooks requested changes
Great update! I really like the list of methods and arguments. Super helpful to anyone learning about Bolt for the first time.

Only feedback is to update the path to the samples directory, which recently changed.

2020-10-05 20:18 UTC, mwbrooks commented on README.md
> +A Python framework to build Slack apps in a flash with the latest platform features. Read the [getting started guide](https://slack.dev/bolt-python/tutorial/getting-started) and look at our [code sam
We updated the `samples/` directory to `examples/` to create some consistency across all our SDKs and frameworks: https://github.com/slackapi/bolt-python/tree/main/examples

We can call it "code samples" or "code examples" but using the word "examples" may help hint what folder to look for:

```suggestion
A Python framework to build Slack apps in a flash with the latest platform features. Read the [getting started guide](https://slack.dev/bolt-python/tutorial/getting-started) and look at our [code examples](https://github.com/slackapi/bolt-python/tree/main/examples) to learn how to build apps using Bolt.
```

2020-10-05 20:18 UTC, mwbrooks commented on README.md
> +Apps typically react to a collection of incoming events, which can correspond [Events API events](https://api.slack.com/events-api), [actions](https://api.slack.com/interactivity/components), [shortc
My grammer isn't top notch, but should this be "correspond to"?

```suggestion
Apps typically react to a collection of incoming events, which can correspond to [Events API events](https://api.slack.com/events-api), [actions](https://api.slack.com/interactivity/components), [shortcuts](https://api.slack.com/interactivity/shortcuts), [slash commands](https://api.slack.com/interactivity/slash-commands) or [options requests](https://api.slack.com/reference/block-kit/block-elements#external_select). For each type of
```

2020-10-05 20:32 UTC, seratch requested changes

2020-10-05 20:32 UTC, seratch commented on README.md
> +// Listen for an event from the Events API
how about mentioning decorator first and then having a list of `app.xxx`?

The recommended way is to use Python decorators.

```python
@app.event(event_type)
def handle_event(event):
    pass
```

Here is a list of available methods to register listeners:
```python
app.event(event_type, matcher)
app.message([pattern ,] fn)
```

Please remove `@` from the examples in the list.

2020-10-05 20:32 UTC, seratch commented on README.md
> +@app.event(event_type, matcher);
remove semicolons in any case

2020-10-05 20:32 UTC, seratch commented on README.md
> +@app.command(/command_name, fn);
```suggestion
@app.command(command_name, fn);
```

2020-10-05 20:32 UTC, seratch commented on README.md
> +// Convenience method to listen to only `message` events using a string or RegExp
There is no `RegExp` in Python. `re.Pattern`.

2020-10-05 20:32 UTC, seratch commented on README.md
> +@app.action({ callback_id: callbackId, block_id: blockId, action_id: actionId }, fn);
Be consistent to use snake_case - keys in dict must have be `"xxx"`
```suggestion
app.action({ "callback_id": callback_id, "block_id": block_id, "action_id": action_id }, fn);
```

2020-10-06 20:08 UTC, seratch approved these changes

2020-10-06 20:08 UTC, seratch commented on README.md
> +app.action({ callback_id: callbackId }, fn)
```suggestion
app.action({"callback_id": callbackId}, fn)
```

2020-10-06 20:09 UTC, merged