addd socket mode and http document in japanese
slackapi/bolt-python pull request #426
Opened 2021-08-04 15:01 UTC by hirosassa

(Describe the goal of this PR. Mention any related Issue numbers)

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [ ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2021-08-04 16:23 UTC, srajiang commented
Woot, big thank you @hirosassa for this contribution 🙌 ! 
I will let @seratch take the lead in providing review on this.

2021-08-05 00:29 UTC, seratch requested changes
@hirosassa Thanks for submitting this awesome pull request! I hope you won't mind receiving these change requests 🙇

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +> 🔒 全てのトークンは安全に保管してください。最低限、パブリックなバージョンコントロールにチェックインすることは避けてください。また、上記の例のように環境変数を介してアクセスするようにしてください。詳細な情報は [best practices for app security](https://api.slack.com/authentication/best-practices).のドキュメ
```suggestion
> 🔒 全てのトークンは安全に保管してください。少なくともパブリックなバージョン管理にチェックインするようなことは避けるべきでしょう。また、上にあった例のように環境変数を介してアクセスするようにしてください。詳細な情報は [アプリのセキュリティのベストプラクティス](https://api.slack.com/authentication/best-practices)のドキュメントを参照してください。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +このようにトークンがあれば、最初の Bolt アプリが作成できます。「`app.py`」ファイルを保存して、コマンドラインで以下を実行します。
```suggestion
このようにトークンさえあれば、最初の Bolt アプリを作成することができます。「`app.py`」ファイルを保存して、コマンドラインで以下を実行します。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +> 💡 このチュートリアルの序盤でソケットモードを有効にしました。ソケットモードを使うことで、アプリがパブリックなHTTPエンドポイントを公開せず、イベントAPIやインタラクティブコンポーネントを利用できるようになります。このことは、開発時やファイヤーウォールの裏からのリクエストを受ける際に便利です。HTTPはホスティングされた環境にデプロイされたアプリや、Slack App Directory
```suggestion
> 💡 このチュートリアルの序盤でソケットモードを有効にしました。ソケットモードを使うことで、アプリが公開された HTTP エンドポイントを公開せずに Events API やインタラクティブコンポーネントを利用できるようになります。このことは、開発時やファイヤーウォールの裏からのリクエストを受ける際に便利です。HTTP での方式はホスティング環境にデプロイするアプリや Slack App Directoryで配布されるアプリに適しています。HTTP での情報については[このドキュメント](/bolt-python/tutorial/getting-started-http)を参照してください。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +それでは、Slackにどのイベントをリッスンするかを教えてあげましょう。
```suggestion
それでは、私たちがどのイベントをリッスンしたいかを Slack に伝えましょう。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +インタラクティブ機能を有効にすると、ボタン、選択メニュー、日付ピッカー、モーダル、ショートカットなどの機能が利用できるようになります。アプリ設定ページの「**Interactivity & Shortcuts**」を見てみましょう。
```suggestion
インタラクティブ機能を有効にすると、ボタン、選択メニュー、日付ピッカー、モーダル、ショートカットなどの機能が利用できるようになります。アプリ設定ページの「**Interactivity & Shortcuts**」にアクセスしてください。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +> 💡 ソケッットモードを有効にしていると、デフォルトで、基本的なインタラクティブ機能が有効になっていることに気づくでしょう。追加のアクションは不要です。HTTPを使っている場合は、Slackに対して、イベントを送信する為のリクエストURLを設定する必要があります。
```suggestion
> 💡 ソケッットモードを有効にしているとき、デフォルトで基本的なインタラクティブ機能が有効になっていることに気づくでしょう。追加のアクションは不要です。もし HTTP を使っている場合、Slack からのイベント送信先である Request URL を設定する必要があります。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +インタラクティブ機能が有効化されている時、ショートカット、モーダル、インタラクティブコンポーネント (ボタンや、選択メニュー、日付ピッカー) とのインタラクションはイベントとしてアプリに対して送信されます。
```suggestion
インタラクティビティが有効化されていれば、ショートカット、モーダル、インタラクティブコンポーネント (例：ボタン、選択メニュー、日付ピッカー) とのインタラクションはイベントとしてあなたのアプリに送信されます。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +- まず、ボタンを含んだメッセージをアプリから送信します。
```suggestion
- まず、インタラクティブコンポーネント（ここではボタン）を含んだメッセージをアプリから送信します。
```

2021-08-05 00:29 UTC, seratch commented on docs/_tutorials/ja_getting_started.md
> +    # Acknowledge the action
```suggestion
    # アクションのリクエストを確認
```

2021-08-05 06:09 UTC, hirosassa reviewed
@seratch Thanks for your review comments! Suggested changes are applied.

2021-08-05 06:45 UTC, seratch approved these changes
Looks great to me 👍

2021-08-05 06:45 UTC, merged

2021-08-05 08:13 UTC, hirosassa commented
Thanks! 🚀