Allow a custom Executor in App
slackapi/bolt-python pull request #453
Opened 2021-08-28 16:54 UTC by chrisbouchard

This pull request adds a `listener_executor` keyword parameter to `App.__init__`, so that the executor for running background listener functions can be customized by the user. It also weakens the type requirement for executors to just `concurrent.futures.Executor`, the abstract base class of executors.

Fixes #452.

### Category (place an `x` in each of the `[ ]`)

* [x] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [ ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2021-08-28 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/bolt-python?pullRequest=453) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/bolt-python?pullRequest=453) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/bolt-python?pullRequest=453) it.</sub>

2021-08-28 17:28 UTC, chrisbouchard commented
I think this is ready for review. One thing I'm unsure of is whether I should update the API documentation. I did update the docstring on `App.__init__`. When I ran `./scripts/generate_api_docs.sh` it updated way more files than I touched.

2021-08-28 21:10 UTC, mwbrooks reviewed
Hey @chrisbouchard, thanks for following up with a pull request! You're awesome 🎉 

The CLA looks good and I've enabled the test workflow to run. ✅ 

I'll let @seratch review your pull request and comment on why generating the documentation changes more files than expected. Regardless, thanks a lot for taking the extra steps to add test and update the docs 🤘🏻

2021-08-29 00:40 UTC, chrisbouchard commented
Ok, I was able to figure out the issue with docs. It looks like a new version of pydoc has been published (0.10.0) that causes content and formatting changes in around 171 doc files. I hard-coded my pydoc version to 0.9.3 to match what's currently checked into main and I got a much more reasonable diff.

2021-08-29 07:09 UTC, seratch commented
@chrisbouchard Thanks for updating the docs but can you revert the change? We usually update the API docs after releasing a version.

2021-08-29 07:15 UTC, seratch requested changes

2021-08-29 07:15 UTC, seratch commented on slack_bolt/app/app.py
> +            listener_executor: Optional executor to run background tasks. If absent, a `ThreadPoolExecutor` will
As the executor is not optional (some executor is required), I prefer "custom" for describing the given one 
```suggestion
            listener_executor: Custom executor to run background tasks. If absent, the default `ThreadPoolExecutor` will
```

2021-08-29 07:15 UTC, seratch commented on slack_bolt/app/app.py
> +        listener_executor: Optional[Executor] = None,
```suggestion
        # Set this one only when you want to customize the executor
        listener_executor: Optional[Executor] = None,
```

2021-08-29 07:33 UTC, chrisbouchard commented
Doc changes reverted, and wording suggestions applied. :+1:

2021-08-29 07:49 UTC, seratch commented on tests/scenario_tests/test_app.py
> +            """A stupid executor that does nothing."""
```suggestion
            """A executor that does nothing for testing"""
```

2021-08-29 07:50 UTC, seratch approved these changes

2021-08-29 07:50 UTC, seratch commented
Thanks for working on this! LGTM

2021-08-29 08:22 UTC, merged