fix 'NoneType' object has no attribute 'utcoffset'
slackapi/bolt-python pull request #522
Opened 2021-11-14 15:38 UTC by paulfab

(Describe the goal of this PR. Mention any related Issue numbers)

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ x] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [ x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2021-11-14 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/bolt-python?pullRequest=522) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/bolt-python?pullRequest=522) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/bolt-python?pullRequest=522) it.</sub>

2021-11-14 23:17 UTC, seratch commented
Hi @paulfab, thanks for taking the time to fix this error! Would you mind signing the CLA (please check the above bot message)? Without having it, we are unable to merge your changes in this repository.

2021-11-14 23:20 UTC, seratch requested changes

2021-11-14 23:20 UTC, seratch commented on examples/django/oauth_app/slack_datastores.py
> -        if "bot_token_expires_at" in b is not None and is_naive(
Obviously, this part was wrong.

2021-11-14 23:20 UTC, seratch commented on examples/django/oauth_app/slack_datastores.py
> +        if i.get("bot_token_expires_at") and is_naive(i["bot_token_expires_at"]):
Can you change this way for consistency?
```suggestion
        if i.get("bot_token_expires_at") is not None and is_naive(i["bot_token_expires_at"]):
```

2021-11-14 23:20 UTC, seratch commented on examples/django/oauth_app/slack_datastores.py
> +        if i.get("user_token_expires_at") and is_naive(i["user_token_expires_at"]):
same as above
```suggestion
        if i.get("user_token_expires_at") is not None and is_naive(i["user_token_expires_at"]):
```

2021-11-15 08:28 UTC, seratch commented
@paulfab Thanks for updating this pull request. Would you mind signing the CLA (please check the above bot message)? Without having it, we are unable to merge your changes in this repository.

2021-11-15 08:30 UTC, paulfab commented
Hey @seratch you are so fast I didnt have the time to comment ^^. Thanks for reviewing the PR, I'm quite reluctant to sign the CLA. You can take ownership of my modest changes and merge it ?

2021-11-15 08:32 UTC, seratch commented
@paulfab Okay, in the case, we can come up with my own pull request instead. Thanks a lot for taking the time to report this!

2021-11-15 08:42 UTC, seratch commented
Let me close this pull request in favor of https://github.com/slackapi/bolt-python/pull/523

2021-11-15 08:42 UTC, closed without merging