Jwong fix 525
slackapi/bolt-python pull request #541
Opened 2021-12-10 01:18 UTC by wongjas

(Describe the goal of this PR. Mention any related Issue numbers)

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [ ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2021-12-10 02:17 UTC, srajiang approved these changes
Changes to english sections look good - thank your for that quality of life improvement!

2021-12-10 06:33 UTC, seratch requested changes

2021-12-10 06:33 UTC, seratch commented on docs/_advanced/ja_lazy_listener.md
> +Lazy リスナー関数は、FaaS 環境への Slack アプリのデプロイを容易にする機能です。この機能は Bolt for Python のみ利用可能で、他の Bolt フレームワークにも対応する予定はありません。
```suggestion
Lazy リスナー関数は、FaaS 環境への Slack アプリのデプロイを容易にする機能です。この機能は Bolt for Python でのみ利用可能で、他の Bolt フレームワークでこの機能に対応することは予定していません。
```

2021-12-10 06:33 UTC, seratch commented on docs/_advanced/ja_lazy_listener.md
> +通常、アクション（action）、コマンド（command）、ショートカット（shortcut）、オプション（options）、およびモーダルからのデータ送信（view_submission）をハンドルするとき、 `ack()` を呼び出し、Slack からのリクエストを 3 秒以内に確認する必要があります。`ack()` を呼び出すと、Slack に HTTP 200 OK レスポンスが送信さ
```suggestion
通常、アクション（action）、コマンド（command）、ショートカット（shortcut）、オプション（options）、およびモーダルからのデータ送信（view_submission）をハンドルするとき、 `ack()` を呼び出し、Slack からのリクエストを 3 秒以内に確認する必要があります。`ack()` を呼び出すと Slack に HTTP ステータスが 200 OK の応答が返されます。こうすることで、アプリがリクエストの応答を処理中であることを Slack に伝えられます。通常であれば、この確認処理を処理関数の最初のステップとして行うことを推奨しています。
```

2021-12-10 06:33 UTC, seratch commented on docs/_advanced/ja_lazy_listener.md
> +しかし、FaaS 環境や類似のランタイムで実行されるアプリでは、HTTP レスポンスを返したあとにスレッドやプロセスの実行を続けることができないため、確認してからの処理という通常のパターンに従うことはできません。代わりに、`process_before_response` フラグを `True` に設定します。このフラグが `True` に設定すると、Bolt はリスナー関数での処理が完了するま
```suggestion
しかし、FaaS 環境や類似のランタイムで実行されるアプリでは、 **HTTP レスポンスを返したあとにスレッドやプロセスの実行を続けることができない** ため、確認の応答を送信した後で時間のかかる処理をするという通常のパターンに従うことができません。こうした環境で動作させるためには、 `process_before_response` フラグを `True` に設定します。このフラグが `True` に設定されている場合、Bolt はリスナー関数での処理が完了するまで HTTP レスポンスの送信を遅延させます。そのため 3 秒以内にリスナーのすべての処理が完了しなかった場合は Slack 上でタイムアウトのエラー表示となってしまいます。また、Events API に応答するリスナーでは明示的な `ack()` メソッドの呼び出しを必要としませんが、この設定を有効にしている場合、リスナーの処理を 3 秒以内に完了させる必要があることにも注意してください。
```

2021-12-10 06:33 UTC, seratch commented on docs/_advanced/ja_lazy_listener.md
> +* `lazy:List[Callable]` : リクエストに関係する、時間のかかるプロセスの処理を担当します。Lazy 関数からは `ack()` にアクセスできません。
```suggestion
処理関数の中で時間のかかる処理を実行できるようにするために、私たちは Lazy リスナーという関数を実行する仕組みを導入しました。Lazy リスナーは、デコレーターとして動作させるのではなく、以下の 2 つのキーワード引数を受け取ります。
* `ack: Callable`: 3 秒以内での `ack()` メソッドの呼び出しを担当します。 
* `lazy: List[Callable]` : リクエストに関する時間のかかる処理のハンドリングを担当します。Lazy 関数からは `ack()` にアクセスすることはできません。
```

2021-12-10 06:33 UTC, seratch commented on docs/_basic/ja_acknowledging_requests.md
> +リクエストの種類によっては、確認で通知方法が異なる場合があります。例えば、外部データソースを使用する選択メニューのオプションのリクエストに対する確認では、適切な[オプション](https://api.slack.com/reference/block-kit/composition-objects#option)のリストとともに `ack()` を呼び出します。モーダルからのデータ送信に対する確
```suggestion
リクエストの種類によっては、確認で通知方法が異なる場合があります。例えば、外部データソースを使用する選択メニューのオプションのリクエストに対する確認では、適切な[オプション](https://api.slack.com/reference/block-kit/composition-objects#option)のリストとともに `ack()` を呼び出します。モーダルからのデータ送信に対する確認では、 `response_action` を渡すことで[モーダルの更新](#update-views-on-submission)などを行えます。
```

2021-12-10 06:33 UTC, seratch commented on docs/_basic/ja_acknowledging_requests.md
> +確認までの猶予は 3 秒しかないため、新しいメッセージの送信や、データベースからの情報の取得というような時間のかかるプロセスは、`ack()` を呼び出した後で行うことをおすすめします。
```suggestion
確認までの猶予は 3 秒しかないため、新しいメッセージの送信やデータベースからの情報の取得といった時間のかかる処理は、`ack()` を呼び出した後で行うことをおすすめします。
```

2021-12-10 06:33 UTC, seratch commented on docs/_basic/ja_acknowledging_requests.md
> + FaaS / serverless 環境を使う場合、 `ack()` するタイミングが異なります。 これについての詳細は [Lazy listeners (FaaS)](#lazy-listeners) にて参照してください。
```suggestion
 FaaS / serverless 環境を使う場合、 `ack()` するタイミングが異なります。 これに関する詳細は [Lazy listeners (FaaS)](#lazy-listeners) を参照してください。 
```

2021-12-12 23:53 UTC, seratch approved these changes

2021-12-13 00:04 UTC, merged