Add Flask app sample that runs on Heroku
slackapi/bolt-python pull request #62
Opened 2020-09-04 11:39 UTC by seratch

```bash
heroku login
heroku create

export $SLACK_BOT_TOKEN=xxx
export SLACK_SIGNING_SECRET=xxx
heroku config:set SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
heroku config:set SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET

git init
git remote add heroku https://git.heroku.com/xxx.git
git push heroku main
```

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/run_tests.sh` after making the changes.

2020-09-04 20:56 UTC, mwbrooks requested changes
I've never seen a Python app setup for Heroku - very cool @seratch!

Left some minor feedback and suggestions.

2020-09-04 20:56 UTC, mwbrooks commented on samples/heroku/main.py
> +# export $SLACK_BOT_TOKEN=xxx
```suggestion
# export SLACK_BOT_TOKEN=xxx
```
I think the `$` can be removed here

2020-09-04 20:56 UTC, mwbrooks commented on samples/heroku/main.py
> +# git push heroku main
nit: do we want to say `main` or `master` here? Git uses `master` by default so `main` may confuse some developer. However, most Heroku users should be familiar with git and know the branch that they want to push.

2020-09-05 00:45 UTC, merged

2020-09-05 00:47 UTC, seratch commented
Congrats for your first-ever commit in this repo, Mike!