add quart adapter
slackapi/bolt-python pull request #620
Opened 2022-03-20 06:12 UTC by sonnens

Add an adapter for Quart ( https://github.com/slackapi/bolt-python/issues/619 )

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [X] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [X] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2022-03-20 06:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/bolt-python?pullRequest=620) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/bolt-python?pullRequest=620) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/bolt-python?pullRequest=620) it.</sub>

2022-03-20 06:58 UTC, seratch commented
Hi @sonnens, thanks for submitting the PR!

There are a few things that we would like you to add:

* Add qaurt dependency to run CI builds [here](https://github.com/slackapi/bolt-python/blob/v1.13.0/setup.py#L72-L96)
* Add unit tests and examples like https://github.com/slackapi/bolt-python/pull/614 nicely did

As I mentioned at https://github.com/slackapi/bolt-python/issues/619#issuecomment-1073182688, we need your (and/or other community members') help for this addition more than usual. It'd be appreciated if you could understand this.

2022-06-30 07:14 UTC, stasfilin requested changes

2022-06-30 07:14 UTC, stasfilin commented on slack_bolt/adapter/quart/async_handler.py
> +            if self.app.oauth_flow is not None:
Hi,
Can we add this to one line below like
`if req.method == "GET" and self.app.oauth_flow is not None`

2025-03-19 17:30 UTC, closed without merging