Add async function capabilities to bolt python
slackapi/bolt-python pull request #704
Opened 2022-08-18 23:16 UTC by WilliamBergamin

The goal of this PR is to add basic remote function support to bolt python **async capabilities**. This contribution does not include the related documentation.

[Here are the modifications to the python template](https://github.com/slack-samples/bolt-python-starter-template/tree/future-async) I've done to use these changes

### Testing
Test these changes manually
#### Setup
you will need a file structure that resembles:
```
.
├── bolt-python-starter-future        # https://github.com/slack-samples/bolt-python-starter-template/tree/future-async
└── bolt-python-future-fork            # https://github.com/WilliamBergamin/bolt-python/tree/future
```
helpful commands
``` zsh
git clone https://github.com/slack-samples/bolt-python-starter-template/tree/future-async
git clone https://github.com/WilliamBergamin/bolt-python/tree/future
```

#### Build
##### Bolt
1. Navigate to your `bolt-python-future-fork` folder
2. set up a python env
    ```zsh
    brew install pyenv
    pyenv install 3.9.6
    python -m venv env_3.9.6
    source env_3.9.6/bin/activate
    ```
3. build the package using the script
    ```zsh
     bash scripts/build_pypi_package.sh 
     ```
##### application
1. Navigate to your `bolt-python-starter-future` folder
2. Set up a pyenv follow the same steps as [Bolt step 2](#bolt)
3. ensure that this dependency is present in the `requirements.txt` file
    ```zsh
     ../bolt-python-future-fork/dist/slack_bolt-1.14.3-py2.py3-none-any.whl
     ```
     this tells pip where your local build of python-bolt is located
4. install the dependencies
    ```zsh
     pip install -r requirements.txt
     ```

#### Run
1. With slack cli (else you need to install the app traditionally)
    ```zsh
     slack trigger create --trigger-def "./trigger.json"
     slack run
     ```
2. Add the app _**Bolt Template App (dev)**_ to a channel in your workspace
3. Find and trigger the Reverse shortcut to start the function
<img width="369" alt="Screen Shot 2022-08-08 at 3 25 01 PM" src="https://user-images.githubusercontent.com/25348381/183504247-ee028efb-c85c-40d8-8783-47f0c5846bdd.png">

### Feed back
I would like to figure out if these changes yield the proper pythonic user experience.
example: Is passing `complete_error` and `complete_success` a correct python way of resolving a function 

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [x] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2022-08-18 23:32 UTC, seratch requested changes
Great work!

2022-08-18 23:32 UTC, seratch commented on slack_bolt/app/async_app.py
> +            async def reverse_string(event, complete_success: CompleteSuccess, complete_error: CompleteError):
```suggestion
            async def reverse_string(event, complete_success: AsyncCompleteSuccess, complete_error: AsyncCompleteError):
```

2022-08-18 23:32 UTC, seratch commented on slack_bolt/context/complete_error/complete_error.py
> -        if self._can_complete():
Can you remove ` _can_complete` instance method in this source file (L34-35)?

2022-08-22 17:10 UTC, filmaj approved these changes

2022-08-24 15:09 UTC, merged