fix-issue-747
slackapi/bolt-python pull request #748
Opened 2022-10-23 23:24 UTC by ntarora

2022-10-23 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/bolt-python?pullRequest=748) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/bolt-python?pullRequest=748) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/bolt-python?pullRequest=748) it.</sub>

2022-10-23 23:24 UTC, ntarora reviewed
Add is_enterprise_install to example

2022-10-23 23:26 UTC, ntarora commented
fix #747

2022-10-24 00:35 UTC, seratch requested changes

2022-10-24 00:35 UTC, seratch commented on examples/sqlalchemy/async_oauth_app.py
> +    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str], is_enterprise_install: Optional[bool]) -> Optional[Bot]:
flake8 detects lint errors. Can you these lines shorter than 125 chars? 

```
Successfully installed flake8-5.0.4 mccabe-0.7.0 pycodestyle-2.9.1 pyflakes-2.5.0
examples/sqlalchemy/async_oauth_app.py:66:126: E501 line too long (148 > 125 characters)
examples/sqlalchemy/async_oauth_app.py:70:126: E501 line too long (130 > 125 characters)
Error: Process completed with exit code 1.
```

2022-10-24 00:37 UTC, seratch commented on examples/sqlalchemy/async_oauth_app.py
> +    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str], is_enterprise_install: Optional[bool]) -> Optional[Bot]:
You can fix these warnings by the following changes:
```diff
diff --git a/examples/sqlalchemy/async_oauth_app.py b/examples/sqlalchemy/async_oauth_app.py
index 5ec7be0..a2c52f0 100644
--- a/examples/sqlalchemy/async_oauth_app.py
+++ b/examples/sqlalchemy/async_oauth_app.py
@@ -63,11 +63,23 @@ class AsyncSQLAlchemyInstallationStore(AsyncInstallationStore):
                 b["client_id"] = self.client_id
                 await database.execute(self.bots.insert(), b)
 
-    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str], is_enterprise_install: Optional[bool]) -> Optional[Bot]:
+    async def async_find_bot(
+        self,
+        *,
+        enterprise_id: Optional[str],
+        team_id: Optional[str],
+        is_enterprise_install: Optional[bool],
+    ) -> Optional[Bot]:
         c = self.bots.c
         query = (
             self.bots.select()
-            .where(and_(c.enterprise_id == enterprise_id, c.team_id == team_id, c.is_enterprise_install == is_enterprise_install))
+            .where(
+                and_(
+                    c.enterprise_id == enterprise_id,
+                    c.team_id == team_id,
+                    c.is_enterprise_install == is_enterprise_install,
+                )
+            )
             .order_by(desc(c.installed_at))
             .limit(1)
         )
```

2022-10-26 08:38 UTC, seratch commented on examples/sqlalchemy/async_oauth_app.py
> +    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str], is_enterprise_install: Optional[bool]) -> Optional[Bot]:
@ntarora Could you push the fix if you have a chance?

2022-10-26 13:57 UTC, ntarora commented
Odd, I did push the formatting fix on my branch. I didn’t get picked up for some reason. Should I close this PR and create a new one? On Oct 26, 2022, at 1:39 AM, Kazuhiro Sera ***@***.***> wrote:﻿
@seratch commented on this pull request.



In examples/sqlalchemy/async_oauth_app.py:
> @@ -63,11 +63,11 @@ async def async_save(self, installation: Installation):
                 b["client_id"] = self.client_id
                 await database.execute(self.bots.insert(), b)
 
-    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str]) -> Optional[Bot]:
+    async def async_find_bot(self, *, enterprise_id: Optional[str], team_id: Optional[str], is_enterprise_install: Optional[bool]) -> Optional[Bot]:

@ntarora Could you push the fix if you have a chance?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-11-04 06:08 UTC, seratch commented
Thanks for your contribution! Your changes are merged at https://github.com/slackapi/bolt-python/commit/f5b40c7830fc0fe681388be0d110054873374a8b and then I've added an additional commit to resolve the flake8 issue on my end.

2022-11-04 06:08 UTC, closed without merging