Fix #754 by adding the async version of Tornado adapter
slackapi/bolt-python pull request #758
Opened 2022-11-04 06:53 UTC by seratch

This pull request resolves #754 by adding the async version of Tornado adapter. Refer to #754 for the context and details.

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [x] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2022-11-04 06:54 UTC, seratch commented on examples/tornado/app.py
> +def log_request(logger, body, next_):
just a minor improvement to eliminate warnings by IDE. See also: https://github.com/slackapi/bolt-python/pull/394

2022-11-04 15:03 UTC, WilliamBergamin requested changes
Great work on this, the code looks good to me 🥇

I ran some test locally that modify the behavior in order to deploy a `sync App` on the `asyncTornado` adapter and this seemed to work 😮 I believe the async handler just executes the sync code as a block similarly to how it would `await` for the `async_dispatch` 

 I'm not sure if this is behavior we want in this adapter, but I think it could be possible for this adapter to accept `async App` and `sync Apps`

2022-11-04 15:12 UTC, seratch commented
@WilliamBergamin Sorry, I don't understand your point yet. Can you elaborate more on the changes you are requesting in your comment?

The intention to add a new adapter in this PR is to enable developers to use AsyncApp along with Tornado. Since AsyncApp relies on AIOHTTP, we need to have a separate module for it. Also, AsyncApp runs "async" functions for handling requests from Slack. This is completely different from the App approach. Let me know if I am missing something here.

2022-11-04 23:43 UTC, seratch commented
>I'm not sure if this is behavior we want in this adapter, but I think it could be possible for this adapter to accept async App and sync Apps

I clearly didn't answer this but indeed it's technically possible to accept both App and AsyncApp in this new adapter. However, perhaps no one will use it. Also, even when a single handler supports both, two separate handlers should exist for sync App users who do not need AIOHTTP at all. Again, just importing AsyncApp requires AIOHTTP installation, which is optional dependency of slack-bolt/slack-sdk. In addition, for consistency with other built-in adapters, I prefer supporting only AsyncApp in this case.

Let's discuss more on this next week.

2022-11-07 16:51 UTC, WilliamBergamin commented
@seratch this makes a lot of sense thank you for the answer 💯

2022-11-07 16:52 UTC, WilliamBergamin approved these changes
This looks good to me 💯

2022-11-08 02:03 UTC, merged