Adding Handling views on close documentation
slackapi/bolt-python pull request #792
Opened 2022-12-17 11:10 UTC by BrandonDalton

Adding Handling Views on close to documentation based on issue #762 with the provided example code provided in #624

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [x ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

2022-12-17 23:49 UTC, seratch requested changes
Thanks for sending this PR! Could you check my comments? After merging this, we'll update the corresponding Japanese translation page too. I will work on it (I am a native Japanese speaker)

2022-12-17 23:49 UTC, seratch commented on docs/_basic/listening_modals.md
> +        "callback_id": "modal-id", # Used when calling view_closed
```suggestion
        "callback_id": "modal-id",  # Used when calling view_closed
```

2022-12-17 23:49 UTC, seratch commented on docs/_basic/listening_modals.md
> +    logger.info("--------------- view_closed handler called ---------------")
Can you remove this?
```suggestion
```

2022-12-18 02:22 UTC, BrandonDalton commented
Thanks @seratch this has been done have a good weekend

2022-12-18 06:22 UTC, seratch approved these changes
Thank you!

2022-12-18 06:23 UTC, merged